### ISSUE TITLE
touched broken for matInput

### ISSUE THREAD

**Issue by russoturisto** [khashayar/ng-trim-value-accessor#11]
Hello,

Using ng-trim with Angular Material appears to break the setting of the "touched" property of the input.

Here is an example:

https://stackblitz.com/edit/angular-68fg1b?file=index.html

The field has an error message defined that should show if the field has the "required" error and has been touched.  However the touched property does not get updated when I click on the field (or when I enter data into it).

I'll gather more info as I debug ...

Thanks, :)

**Comment by russoturisto** [comment]
So, just injecting NgControl as a member variable into the directive appears to fix the problem. :)

**Comment by khashayar** [comment]
@russoturisto Can this issue be closed or do you still facing any problems?

**Comment by dankahle** [comment]
This is still an issue. Not sure why you closed it. If you look at his stackblitz examples, it's easy to see. I just got the latest material and still happening. For some reason, his injecting NgControl into the constructor does the trick. It's one of several material issues. Several components have their own ControlValueAccessor and you can only have one of those, input[matAutoComplete] is one, and the code crashes on that, messes up my app at least. I put your opt out class on it and all worked fine with the rest of my inputs, but I notice that ngModel.touched isn't happening, so this is still an issue.
