### ISSUE TITLE
I get "More than one custom value accessor matches form control with unspecified name attribute"

### ISSUE THREAD

**Issue by mkgn** [khashayar/ng-trim-value-accessor#17]
When I try to use this I get this error message.
More than one custom value accessor matches form control with unspecified name attribute

But I don't have any other in the project.

**Comment by khashayar** [comment]
It's probably because you are using another 3rd party component, which is trying to attach a custom value accessor to your form controls. To remedy that, just try to add the `class="ng-trim-ignore"` attribute to your form control.
