### ISSUE TITLE
Does not work with Ivy

### ISSUE THREAD

**Issue by mickaeltr** [khashayar/ng-trim-value-accessor#23]
Hello,

ng-trim-value-accessor does not seem to work with [Ivy](https://next.angular.io/guide/ivy) as it raised the following error:
> ERROR in There is no format with import statements in '…/node_modules/ng-trim-value-accessor' entry-point.

That seems related to: https://github.com/angular/angular/issues/29564

Thanks

**Comment by petebacondarwin** [comment]
@mickaeltr - Please try with Angular v8.2.0-next.0 - that error should be fixed.

**Comment by mickaeltr** [comment]
I ended up making my own up-to-date `ng-trim-value-accessor` but I will give it another try when Angular 8.2 is out.
