### ISSUE TITLE
Fails Typescript compilation - DefaultValueAccessor now has a 3rd argument

### ISSUE THREAD

**Issue by chrishandorf** [khashayar/ng-trim-value-accessor#3]
trim-value-accessor.ts:

constructor(private renderer: Renderer, private elRef: ElementRef, private compositionMode: boolean) {
    super(renderer, elRef, compositionMode);
  }

**Comment by khashayar** [comment]
What version of Angular are you using? This could be the issue if you are using Angular > 4.0

**Comment by khashayar** [comment]
Fixed in release v0.0.5
