### ISSUE TITLE
ng build --prod fails with `...src/trim-value-accessor.ts has no selector, please add it!`

### ISSUE THREAD

**Issue by BenAychh** [khashayar/ng-trim-value-accessor#6]
I created a new project just to make sure it wasn't me: https://github.com/BenAychh/ng-trim-value-accessor-tester

All of the sudden, angular gives me this error when I try to do anything with AOT (`ng build --prod` or `ng build --aot=true`):

ERROR in Directive TrimValueAccessor in /Users/benhernandez/ng-trim-value-accessor-tester/node_modules/ng-trim-value-accessor/src/trim-value-accessor.ts has no selector, please add it!

I would open a PR and fix it but I have no idea what is wrong with your selector. Everything looks correct to me?

**Comment by khashayar** [comment]
Thanks for reporting the issue. It should be fixed in next release.
